services:
  api:
    image: clickfila/clickfila-api:latest
    container_name: clickFila_spring_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      # Database injection
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

      # Redis config (fixed for container internal network)
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis

      # Security & External APIs injection
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - MAIL_FROM=${MAIL_FROM}

      # OAuth2 & Cookies Redirect
      - FRONTEND_URL=${FRONTEND_URL}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - COOKIE_SECURE=${COOKIE_SECURE}

      # Disables Spring's native Docker Compose integration in production
      - SPRING_DOCKER_COMPOSE_ENABLED=false

  redis:
    image: redis:7
    container_name: clickFila_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  alloy:
    image: grafana/alloy:latest
    container_name: clickFila_alloy
    restart: unless-stopped
    pid: host
    volumes:
        - ./config.alloy:/etc/alloy/config.alloy:ro
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    environment:
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_USERNAME=${GRAFANA_USERNAME}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - api

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: clickFila_cloudFlare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - TUNNEL_TRANSPORT_PROTOCOL=http2
